.Dd October 15, 2004
.Dt LOCATE.CODE 8  
.Os Darwin
.Sh NAME
.Nm locate.code, locate.bigram
.Nd sorted list compressor
.Sh SYNOPSIS
.Nm locate.code
.Nm locate.bigram
.Sh DESCRIPTION
.Nm locate.code
and
.Nm locate.bigram
are programs used by
.Xr locate 1
during the indexing process.
.Nm locate.code
and
.Nm locate.bigram
should not be run manually.
.Sh SEE ALSO
.Xr locate 1 ,
.Xr locate.updatedb 8
