.\" Copyright (c) 1983, 1991, 1993
.\"	The Regents of the University of California.  All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"	This product includes software developed by the University of
.\"	California, Berkeley and its contributors.
.\" 4. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"	@(#)tftpd.8	8.1 (Berkeley) 6/4/93
.\" $FreeBSD: src/libexec/tftpd/tftpd.8,v 1.15 2001/07/15 07:53:42 dd Exp $
.\"
.Dd August 29, 2003
.Dt KDUMPD 8
.Os
.Sh NAME
.Nm kdumpd
.Nd Mac OS X remote kernel core dump server
.Sh SYNOPSIS
.Nm /usr/libexec/kdumpd
.Op Ar directory
.Sh DESCRIPTION
.Nm Kdumpd
is a server which receives
kernel states in the form of
a core dump from a remote 
Mac OS X machine.
The
.Tn kdumpd
server operates
on UDP port 1069, although this
may be configurable in the future.
The server should be started by
.Xr inetd 8 .
.Pp
The server should have the user ID
with the lowest possible privilege,
usually the user "nobody". 
The directory specified as a server 
program argument in
.Pa /etc/inetd.conf
directs the server to store kernel cores
in that directory and nowhere else. 
The server returns an EEXIST error
to the remote kernel if it receives a
request for an existing file - i.e.
only new files can be created. The server
also disallows path specifications in the
incoming file name. 
.Sh HISTORY
The
.Nm
command is based on Berkeley
.Xr tftpd 8
by way of FreeBSD, with several modifications.
