.Dd 6/12/14
.Dt mptcp_client 1
.Os Darwin
.Sh NAME
.Nm mptcp_client
.Nd Tool to exercise MPTCP.
.Sh SYNOPSIS
.Nm
.Ar hostname
.Ar port
.Ar reqlen
.Ar rsplen
.Ar times
.Ar alt_addr
.Ar 0
.Ar longlived
.Sh DESCRIPTION
.Nm
is as an MPTCP client test tool that use the
.Xr socket 2
API.
