.Dd 5/7/2015
.Dt ecnprobe 1
.Os Darwin
.Sh NAME
.Nm ecnprobe
.Nd Tool to probe for TCP ECN related incompatibilities in the network
.Sh SYNOPSIS
.Nm
.Op Fl n Ar target hostname or ipaddress
.Op Fl p Ar target port
.Op Fl m Ar mss
.Op Fl M Ar mtu
.Op Fl w Ar source port
.Op Fl s Ar source ip address
.Op Fl f Ar file name to get
.Op Fl d Ar interface name
.Sh DESCRIPTION
The
.Nm
utility can be used to test TCP ECN related incompatibilities in the network.
