## Automatically generated by gen-single-binary.sh.  DO NOT EDIT BY HAND!
src_libsinglebin_dir_a_DEPENDENCIES = src/libsinglebin_ls.a
src_libsinglebin_vdir_a_DEPENDENCIES = src/libsinglebin_ls.a
src_libsinglebin_arch_a_DEPENDENCIES = src/libsinglebin_uname.a
# Command arch
noinst_LIBRARIES += src/libsinglebin_arch.a
src_libsinglebin_arch_a_SOURCES = src/coreutils-arch.c
src_libsinglebin_arch_a_ldadd =  src/libsinglebin_uname.a
src_libsinglebin_arch_a_CFLAGS = "-Dmain=single_binary_main_arch (int, char **);  int single_binary_main_arch"  -Dusage=_usage_arch $(src_coreutils_CFLAGS)
# Command hostname
noinst_LIBRARIES += src/libsinglebin_hostname.a
src_libsinglebin_hostname_a_SOURCES = src/hostname.c
src_libsinglebin_hostname_a_ldadd =   $(GETHOSTNAME_LIB)
src_libsinglebin_hostname_a_CFLAGS = "-Dmain=single_binary_main_hostname (int, char **);  int single_binary_main_hostname"  -Dusage=_usage_hostname $(src_coreutils_CFLAGS)
# Command chroot
noinst_LIBRARIES += src/libsinglebin_chroot.a
src_libsinglebin_chroot_a_SOURCES = src/chroot.c
src_libsinglebin_chroot_a_CFLAGS = "-Dmain=single_binary_main_chroot (int, char **);  int single_binary_main_chroot"  -Dusage=_usage_chroot $(src_coreutils_CFLAGS)
# Command df
noinst_LIBRARIES += src/libsinglebin_df.a
src_libsinglebin_df_a_SOURCES =   src/df.c src/find-mount-point.c
src_libsinglebin_df_a_CFLAGS = "-Dmain=single_binary_main_df (int, char **);  int single_binary_main_df"  -Dusage=_usage_df $(src_coreutils_CFLAGS)
# Command hostid
noinst_LIBRARIES += src/libsinglebin_hostid.a
src_libsinglebin_hostid_a_SOURCES = src/hostid.c
src_libsinglebin_hostid_a_CFLAGS = "-Dmain=single_binary_main_hostid (int, char **);  int single_binary_main_hostid"  -Dusage=_usage_hostid $(src_coreutils_CFLAGS)
# Command nice
noinst_LIBRARIES += src/libsinglebin_nice.a
src_libsinglebin_nice_a_SOURCES = src/nice.c
src_libsinglebin_nice_a_CFLAGS = "-Dmain=single_binary_main_nice (int, char **);  int single_binary_main_nice"  -Dusage=_usage_nice $(src_coreutils_CFLAGS)
# Command pinky
noinst_LIBRARIES += src/libsinglebin_pinky.a
src_libsinglebin_pinky_a_SOURCES = src/pinky.c
src_libsinglebin_pinky_a_ldadd =   $(GETADDRINFO_LIB)
src_libsinglebin_pinky_a_CFLAGS = "-Dmain=single_binary_main_pinky (int, char **);  int single_binary_main_pinky"  -Dusage=_usage_pinky $(src_coreutils_CFLAGS)
# Command stdbuf
noinst_LIBRARIES += src/libsinglebin_stdbuf.a
src_libsinglebin_stdbuf_a_SOURCES = src/stdbuf.c
src_libsinglebin_stdbuf_a_CFLAGS = "-Dmain=single_binary_main_stdbuf (int, char **);  int single_binary_main_stdbuf"  -Dusage=_usage_stdbuf $(src_coreutils_CFLAGS)
# Command stty
noinst_LIBRARIES += src/libsinglebin_stty.a
src_libsinglebin_stty_a_SOURCES = src/stty.c
src_libsinglebin_stty_a_CFLAGS = "-Dmain=single_binary_main_stty (int, char **);  int single_binary_main_stty"  -Dusage=_usage_stty $(src_coreutils_CFLAGS)
# Command timeout
noinst_LIBRARIES += src/libsinglebin_timeout.a
src_libsinglebin_timeout_a_SOURCES =   src/timeout.c src/operand2sig.c
src_libsinglebin_timeout_a_ldadd =   $(LIB_TIMER_TIME)
src_libsinglebin_timeout_a_CFLAGS = "-Dmain=single_binary_main_timeout (int, char **);  int single_binary_main_timeout"  -Dusage=_usage_timeout $(src_coreutils_CFLAGS)
# Command uptime
noinst_LIBRARIES += src/libsinglebin_uptime.a
src_libsinglebin_uptime_a_SOURCES = src/uptime.c
src_libsinglebin_uptime_a_ldadd =   $(GETLOADAVG_LIBS)
src_libsinglebin_uptime_a_CFLAGS = "-Dmain=single_binary_main_uptime (int, char **);  int single_binary_main_uptime"  -Dusage=_usage_uptime $(src_coreutils_CFLAGS)
# Command users
noinst_LIBRARIES += src/libsinglebin_users.a
src_libsinglebin_users_a_SOURCES = src/users.c
src_libsinglebin_users_a_CFLAGS = "-Dmain=single_binary_main_users (int, char **);  int single_binary_main_users"  -Dusage=_usage_users $(src_coreutils_CFLAGS)
# Command who
noinst_LIBRARIES += src/libsinglebin_who.a
src_libsinglebin_who_a_SOURCES = src/who.c
src_libsinglebin_who_a_ldadd =   $(GETADDRINFO_LIB)
src_libsinglebin_who_a_CFLAGS = "-Dmain=single_binary_main_who (int, char **);  int single_binary_main_who"  -Dusage=_usage_who $(src_coreutils_CFLAGS)
# Command _
noinst_LIBRARIES += src/libsinglebin__.a
src_libsinglebin___a_SOURCES =   src/lbracket.c
src_libsinglebin___a_ldadd =   $(src_test_LDADD)
src_libsinglebin___a_CFLAGS = "-Dmain=single_binary_main__ (int, char **);  int single_binary_main__"  -Dusage=_usage__ $(src_coreutils_CFLAGS)
# Command b2sum
noinst_LIBRARIES += src/libsinglebin_b2sum.a
src_libsinglebin_b2sum_a_SOURCES =   src/md5sum.c src/blake2/blake2.h src/blake2/blake2-impl.h src/blake2/blake2b-ref.c src/blake2/b2sum.c src/blake2/b2sum.h
src_libsinglebin_b2sum_a_CFLAGS = "-Dmain=single_binary_main_b2sum (int, char **);  int single_binary_main_b2sum"  -Dusage=_usage_b2sum $(src_coreutils_CFLAGS)
src_libsinglebin_b2sum_a_CPPFLAGS =   -include config.h -DHASH_ALGO_BLAKE2=1 $(AM_CPPFLAGS)
# Command base64
noinst_LIBRARIES += src/libsinglebin_base64.a
src_libsinglebin_base64_a_SOURCES = src/base64.c
src_libsinglebin_base64_a_CFLAGS = "-Dmain=single_binary_main_base64 (int, char **);  int single_binary_main_base64"  -Dusage=_usage_base64 $(src_coreutils_CFLAGS)
src_libsinglebin_base64_a_CPPFLAGS =   -DBASE_TYPE=64 $(AM_CPPFLAGS)
# Command base32
noinst_LIBRARIES += src/libsinglebin_base32.a
src_libsinglebin_base32_a_SOURCES =   src/base64.c
src_libsinglebin_base32_a_CFLAGS = "-Dmain=single_binary_main_base32 (int, char **);  int single_binary_main_base32"  -Dusage=_usage_base32 $(src_coreutils_CFLAGS)
src_libsinglebin_base32_a_CPPFLAGS =   -DBASE_TYPE=32 $(AM_CPPFLAGS)
# Command basename
noinst_LIBRARIES += src/libsinglebin_basename.a
src_libsinglebin_basename_a_SOURCES = src/basename.c
src_libsinglebin_basename_a_CFLAGS = "-Dmain=single_binary_main_basename (int, char **);  int single_binary_main_basename"  -Dusage=_usage_basename $(src_coreutils_CFLAGS)
# Command cat
noinst_LIBRARIES += src/libsinglebin_cat.a
src_libsinglebin_cat_a_SOURCES = src/cat.c
src_libsinglebin_cat_a_CFLAGS = "-Dmain=single_binary_main_cat (int, char **);  int single_binary_main_cat"  -Dusage=_usage_cat $(src_coreutils_CFLAGS)
# Command chcon
noinst_LIBRARIES += src/libsinglebin_chcon.a
src_libsinglebin_chcon_a_SOURCES = src/chcon.c
src_libsinglebin_chcon_a_ldadd =   $(LIB_SELINUX)
src_libsinglebin_chcon_a_CFLAGS = "-Dmain=single_binary_main_chcon (int, char **);  int single_binary_main_chcon"  -Dusage=_usage_chcon $(src_coreutils_CFLAGS)
# Command chgrp
noinst_LIBRARIES += src/libsinglebin_chgrp.a
src_libsinglebin_chgrp_a_SOURCES =   src/chgrp.c src/chown-core.c
src_libsinglebin_chgrp_a_CFLAGS = "-Dmain=single_binary_main_chgrp (int, char **);  int single_binary_main_chgrp"  -Dusage=_usage_chgrp $(src_coreutils_CFLAGS)
# Command chmod
noinst_LIBRARIES += src/libsinglebin_chmod.a
src_libsinglebin_chmod_a_SOURCES = src/chmod.c
src_libsinglebin_chmod_a_CFLAGS = "-Dmain=single_binary_main_chmod (int, char **);  int single_binary_main_chmod"  -Dusage=_usage_chmod $(src_coreutils_CFLAGS)
# Command chown
noinst_LIBRARIES += src/libsinglebin_chown.a
src_libsinglebin_chown_a_SOURCES =   src/chown.c src/chown-core.c
src_libsinglebin_chown_a_CFLAGS = "-Dmain=single_binary_main_chown (int, char **);  int single_binary_main_chown"  -Dusage=_usage_chown $(src_coreutils_CFLAGS)
# Command cksum
noinst_LIBRARIES += src/libsinglebin_cksum.a
src_libsinglebin_cksum_a_SOURCES = src/cksum.c
src_libsinglebin_cksum_a_CFLAGS = "-Dmain=single_binary_main_cksum (int, char **);  int single_binary_main_cksum"  -Dusage=_usage_cksum $(src_coreutils_CFLAGS)
# Command comm
noinst_LIBRARIES += src/libsinglebin_comm.a
src_libsinglebin_comm_a_SOURCES = src/comm.c
src_libsinglebin_comm_a_CFLAGS = "-Dmain=single_binary_main_comm (int, char **);  int single_binary_main_comm"  -Dusage=_usage_comm $(src_coreutils_CFLAGS)
# Command cp
noinst_LIBRARIES += src/libsinglebin_cp.a
src_libsinglebin_cp_a_SOURCES =   src/cp.c $(copy_sources) $(selinux_sources)
src_libsinglebin_cp_a_ldadd =   $(copy_ldadd)
src_libsinglebin_cp_a_CFLAGS = "-Dmain=single_binary_main_cp (int, char **);  int single_binary_main_cp"  -Dusage=_usage_cp $(src_coreutils_CFLAGS)
# Command csplit
noinst_LIBRARIES += src/libsinglebin_csplit.a
src_libsinglebin_csplit_a_SOURCES = src/csplit.c
src_libsinglebin_csplit_a_CFLAGS = "-Dmain=single_binary_main_csplit (int, char **);  int single_binary_main_csplit"  -Dusage=_usage_csplit $(src_coreutils_CFLAGS)
# Command cut
noinst_LIBRARIES += src/libsinglebin_cut.a
src_libsinglebin_cut_a_SOURCES =   src/cut.c src/set-fields.c
src_libsinglebin_cut_a_CFLAGS = "-Dmain=single_binary_main_cut (int, char **);  int single_binary_main_cut"  -Dusage=_usage_cut $(src_coreutils_CFLAGS)
# Command date
noinst_LIBRARIES += src/libsinglebin_date.a
src_libsinglebin_date_a_SOURCES = src/date.c
src_libsinglebin_date_a_ldadd =   $(LIB_CLOCK_GETTIME)
src_libsinglebin_date_a_CFLAGS = "-Dmain=single_binary_main_date (int, char **);  int single_binary_main_date"  -Dusage=_usage_date $(src_coreutils_CFLAGS)
# Command dd
noinst_LIBRARIES += src/libsinglebin_dd.a
src_libsinglebin_dd_a_SOURCES = src/dd.c
src_libsinglebin_dd_a_ldadd =   $(LIB_GETHRXTIME)  $(LIB_FDATASYNC)
src_libsinglebin_dd_a_CFLAGS = "-Dmain=single_binary_main_dd (int, char **);  int single_binary_main_dd"  -Dusage=_usage_dd $(src_coreutils_CFLAGS)
# Command dir
noinst_LIBRARIES += src/libsinglebin_dir.a
src_libsinglebin_dir_a_SOURCES = src/coreutils-dir.c
src_libsinglebin_dir_a_ldadd =   $(src_ls_LDADD) src/libsinglebin_ls.a
src_libsinglebin_dir_a_CFLAGS = "-Dmain=single_binary_main_dir (int, char **);  int single_binary_main_dir"  -Dusage=_usage_dir $(src_coreutils_CFLAGS)
# Command dircolors
noinst_LIBRARIES += src/libsinglebin_dircolors.a
src_libsinglebin_dircolors_a_SOURCES = src/dircolors.c
src_libsinglebin_dircolors_a_CFLAGS = "-Dmain=single_binary_main_dircolors (int, char **);  int single_binary_main_dircolors"  -Dusage=_usage_dircolors $(src_coreutils_CFLAGS)
# Command dirname
noinst_LIBRARIES += src/libsinglebin_dirname.a
src_libsinglebin_dirname_a_SOURCES = src/dirname.c
src_libsinglebin_dirname_a_CFLAGS = "-Dmain=single_binary_main_dirname (int, char **);  int single_binary_main_dirname"  -Dusage=_usage_dirname $(src_coreutils_CFLAGS)
# Command du
noinst_LIBRARIES += src/libsinglebin_du.a
src_libsinglebin_du_a_SOURCES = src/du.c
src_libsinglebin_du_a_CFLAGS = "-Dmain=single_binary_main_du (int, char **);  int single_binary_main_du"  -Dusage=_usage_du $(src_coreutils_CFLAGS)
# Command echo
noinst_LIBRARIES += src/libsinglebin_echo.a
src_libsinglebin_echo_a_SOURCES = src/echo.c
src_libsinglebin_echo_a_CFLAGS = "-Dmain=single_binary_main_echo (int, char **);  int single_binary_main_echo"  -Dusage=_usage_echo $(src_coreutils_CFLAGS)
# Command env
noinst_LIBRARIES += src/libsinglebin_env.a
src_libsinglebin_env_a_SOURCES = src/env.c
src_libsinglebin_env_a_CFLAGS = "-Dmain=single_binary_main_env (int, char **);  int single_binary_main_env"  -Dusage=_usage_env $(src_coreutils_CFLAGS)
# Command expand
noinst_LIBRARIES += src/libsinglebin_expand.a
src_libsinglebin_expand_a_SOURCES =   src/expand.c src/expand-common.c
src_libsinglebin_expand_a_CFLAGS = "-Dmain=single_binary_main_expand (int, char **);  int single_binary_main_expand"  -Dusage=_usage_expand $(src_coreutils_CFLAGS)
# Command expr
noinst_LIBRARIES += src/libsinglebin_expr.a
src_libsinglebin_expr_a_SOURCES = src/expr.c
src_libsinglebin_expr_a_ldadd =   $(LIB_GMP)
src_libsinglebin_expr_a_CFLAGS = "-Dmain=single_binary_main_expr (int, char **);  int single_binary_main_expr"  -Dusage=_usage_expr $(src_coreutils_CFLAGS)
# Command factor
noinst_LIBRARIES += src/libsinglebin_factor.a
src_libsinglebin_factor_a_SOURCES = src/factor.c
src_libsinglebin_factor_a_ldadd =   $(LIB_GMP)  $(LIBICONV)
src_libsinglebin_factor_a_CFLAGS = "-Dmain=single_binary_main_factor (int, char **);  int single_binary_main_factor"  -Dusage=_usage_factor $(src_coreutils_CFLAGS)
# Command false
noinst_LIBRARIES += src/libsinglebin_false.a
src_libsinglebin_false_a_SOURCES = src/false.c
src_libsinglebin_false_a_CFLAGS = "-Dmain=single_binary_main_false (int, char **);  int single_binary_main_false"  -Dusage=_usage_false $(src_coreutils_CFLAGS)
# Command fmt
noinst_LIBRARIES += src/libsinglebin_fmt.a
src_libsinglebin_fmt_a_SOURCES = src/fmt.c
src_libsinglebin_fmt_a_CFLAGS = "-Dmain=single_binary_main_fmt (int, char **);  int single_binary_main_fmt"  -Dusage=_usage_fmt $(src_coreutils_CFLAGS)
# Command fold
noinst_LIBRARIES += src/libsinglebin_fold.a
src_libsinglebin_fold_a_SOURCES = src/fold.c
src_libsinglebin_fold_a_CFLAGS = "-Dmain=single_binary_main_fold (int, char **);  int single_binary_main_fold"  -Dusage=_usage_fold $(src_coreutils_CFLAGS)
# Command ginstall
noinst_LIBRARIES += src/libsinglebin_ginstall.a
src_libsinglebin_ginstall_a_SOURCES =   src/install.c src/prog-fprintf.c $(copy_sources) $(selinux_sources)
src_libsinglebin_ginstall_a_ldadd =   $(copy_ldadd)  $(LIB_SELINUX)  $(LIB_CLOCK_GETTIME)
src_libsinglebin_ginstall_a_CFLAGS = "-Dmain=single_binary_main_ginstall (int, char **);  int single_binary_main_ginstall"  -Dusage=_usage_ginstall $(src_coreutils_CFLAGS)
src_libsinglebin_ginstall_a_CPPFLAGS =   -DENABLE_MATCHPATHCON=1 $(AM_CPPFLAGS)
# Command groups
noinst_LIBRARIES += src/libsinglebin_groups.a
src_libsinglebin_groups_a_SOURCES =   src/groups.c src/group-list.c
src_libsinglebin_groups_a_CFLAGS = "-Dmain=single_binary_main_groups (int, char **);  int single_binary_main_groups"  -Dusage=_usage_groups $(src_coreutils_CFLAGS)
# Command head
noinst_LIBRARIES += src/libsinglebin_head.a
src_libsinglebin_head_a_SOURCES = src/head.c
src_libsinglebin_head_a_CFLAGS = "-Dmain=single_binary_main_head (int, char **);  int single_binary_main_head"  -Dusage=_usage_head $(src_coreutils_CFLAGS)
# Command id
noinst_LIBRARIES += src/libsinglebin_id.a
src_libsinglebin_id_a_SOURCES =   src/id.c src/group-list.c
src_libsinglebin_id_a_ldadd =   $(LIB_SELINUX)  $(LIB_SMACK)
src_libsinglebin_id_a_CFLAGS = "-Dmain=single_binary_main_id (int, char **);  int single_binary_main_id"  -Dusage=_usage_id $(src_coreutils_CFLAGS)
# Command join
noinst_LIBRARIES += src/libsinglebin_join.a
src_libsinglebin_join_a_SOURCES = src/join.c
src_libsinglebin_join_a_CFLAGS = "-Dmain=single_binary_main_join (int, char **);  int single_binary_main_join"  -Dusage=_usage_join $(src_coreutils_CFLAGS)
# Command kill
noinst_LIBRARIES += src/libsinglebin_kill.a
src_libsinglebin_kill_a_SOURCES =   src/kill.c src/operand2sig.c
src_libsinglebin_kill_a_ldadd =   $(LIBTHREAD)
src_libsinglebin_kill_a_CFLAGS = "-Dmain=single_binary_main_kill (int, char **);  int single_binary_main_kill"  -Dusage=_usage_kill $(src_coreutils_CFLAGS)
# Command link
noinst_LIBRARIES += src/libsinglebin_link.a
src_libsinglebin_link_a_SOURCES = src/link.c
src_libsinglebin_link_a_CFLAGS = "-Dmain=single_binary_main_link (int, char **);  int single_binary_main_link"  -Dusage=_usage_link $(src_coreutils_CFLAGS)
# Command ln
noinst_LIBRARIES += src/libsinglebin_ln.a
src_libsinglebin_ln_a_SOURCES =   src/ln.c src/force-link.c src/force-link.h src/relpath.c src/relpath.h
src_libsinglebin_ln_a_CFLAGS = "-Dmain=single_binary_main_ln (int, char **);  int single_binary_main_ln"  -Dusage=_usage_ln $(src_coreutils_CFLAGS)
# Command logname
noinst_LIBRARIES += src/libsinglebin_logname.a
src_libsinglebin_logname_a_SOURCES = src/logname.c
src_libsinglebin_logname_a_CFLAGS = "-Dmain=single_binary_main_logname (int, char **);  int single_binary_main_logname"  -Dusage=_usage_logname $(src_coreutils_CFLAGS)
# Command ls
noinst_LIBRARIES += src/libsinglebin_ls.a
src_libsinglebin_ls_a_SOURCES =   src/ls.c src/ls-ls.c
src_libsinglebin_ls_a_ldadd =   $(LIB_SELINUX)  $(LIB_SMACK)  $(LIB_CLOCK_GETTIME)  $(LIB_CAP)  $(LIB_HAS_ACL)
src_libsinglebin_ls_a_CFLAGS = "-Dmain=single_binary_main_ls (int, char **);  int single_binary_main_ls"  -Dusage=_usage_ls $(src_coreutils_CFLAGS)
# Command md5sum
noinst_LIBRARIES += src/libsinglebin_md5sum.a
src_libsinglebin_md5sum_a_SOURCES = src/md5sum.c
src_libsinglebin_md5sum_a_ldadd =   $(LIB_CRYPTO)
src_libsinglebin_md5sum_a_CFLAGS = "-Dmain=single_binary_main_md5sum (int, char **);  int single_binary_main_md5sum"  -Dusage=_usage_md5sum $(src_coreutils_CFLAGS)
src_libsinglebin_md5sum_a_CPPFLAGS =   -DHASH_ALGO_MD5=1 $(AM_CPPFLAGS)
# Command mkdir
noinst_LIBRARIES += src/libsinglebin_mkdir.a
src_libsinglebin_mkdir_a_SOURCES =   src/mkdir.c src/prog-fprintf.c $(selinux_sources)
src_libsinglebin_mkdir_a_ldadd =   $(LIB_SELINUX)  $(LIB_SMACK)
src_libsinglebin_mkdir_a_CFLAGS = "-Dmain=single_binary_main_mkdir (int, char **);  int single_binary_main_mkdir"  -Dusage=_usage_mkdir $(src_coreutils_CFLAGS)
# Command mkfifo
noinst_LIBRARIES += src/libsinglebin_mkfifo.a
src_libsinglebin_mkfifo_a_SOURCES =   src/mkfifo.c $(selinux_sources)
src_libsinglebin_mkfifo_a_ldadd =   $(LIB_SELINUX)  $(LIB_SMACK)
src_libsinglebin_mkfifo_a_CFLAGS = "-Dmain=single_binary_main_mkfifo (int, char **);  int single_binary_main_mkfifo"  -Dusage=_usage_mkfifo $(src_coreutils_CFLAGS)
# Command mknod
noinst_LIBRARIES += src/libsinglebin_mknod.a
src_libsinglebin_mknod_a_SOURCES =   src/mknod.c $(selinux_sources)
src_libsinglebin_mknod_a_ldadd =   $(LIB_SELINUX)  $(LIB_SMACK)
src_libsinglebin_mknod_a_CFLAGS = "-Dmain=single_binary_main_mknod (int, char **);  int single_binary_main_mknod"  -Dusage=_usage_mknod $(src_coreutils_CFLAGS)
# Command mktemp
noinst_LIBRARIES += src/libsinglebin_mktemp.a
src_libsinglebin_mktemp_a_SOURCES = src/mktemp.c
src_libsinglebin_mktemp_a_CFLAGS = "-Dmain=single_binary_main_mktemp (int, char **);  int single_binary_main_mktemp"  -Dusage=_usage_mktemp $(src_coreutils_CFLAGS)
# Command mv
noinst_LIBRARIES += src/libsinglebin_mv.a
src_libsinglebin_mv_a_SOURCES =   src/mv.c src/remove.c $(copy_sources) $(selinux_sources)
src_libsinglebin_mv_a_ldadd =   $(copy_ldadd)  $(remove_ldadd)
src_libsinglebin_mv_a_CFLAGS = "-Dmain=single_binary_main_mv (int, char **);  int single_binary_main_mv"  -Dusage=_usage_mv $(src_coreutils_CFLAGS)
# Command nl
noinst_LIBRARIES += src/libsinglebin_nl.a
src_libsinglebin_nl_a_SOURCES = src/nl.c
src_libsinglebin_nl_a_CFLAGS = "-Dmain=single_binary_main_nl (int, char **);  int single_binary_main_nl"  -Dusage=_usage_nl $(src_coreutils_CFLAGS)
# Command nproc
noinst_LIBRARIES += src/libsinglebin_nproc.a
src_libsinglebin_nproc_a_SOURCES = src/nproc.c
src_libsinglebin_nproc_a_CFLAGS = "-Dmain=single_binary_main_nproc (int, char **);  int single_binary_main_nproc"  -Dusage=_usage_nproc $(src_coreutils_CFLAGS)
# Command nohup
noinst_LIBRARIES += src/libsinglebin_nohup.a
src_libsinglebin_nohup_a_SOURCES = src/nohup.c
src_libsinglebin_nohup_a_CFLAGS = "-Dmain=single_binary_main_nohup (int, char **);  int single_binary_main_nohup"  -Dusage=_usage_nohup $(src_coreutils_CFLAGS)
# Command numfmt
noinst_LIBRARIES += src/libsinglebin_numfmt.a
src_libsinglebin_numfmt_a_SOURCES =   src/numfmt.c src/set-fields.c
src_libsinglebin_numfmt_a_CFLAGS = "-Dmain=single_binary_main_numfmt (int, char **);  int single_binary_main_numfmt"  -Dusage=_usage_numfmt $(src_coreutils_CFLAGS)
# Command od
noinst_LIBRARIES += src/libsinglebin_od.a
src_libsinglebin_od_a_SOURCES = src/od.c
src_libsinglebin_od_a_CFLAGS = "-Dmain=single_binary_main_od (int, char **);  int single_binary_main_od"  -Dusage=_usage_od $(src_coreutils_CFLAGS)
# Command paste
noinst_LIBRARIES += src/libsinglebin_paste.a
src_libsinglebin_paste_a_SOURCES = src/paste.c
src_libsinglebin_paste_a_CFLAGS = "-Dmain=single_binary_main_paste (int, char **);  int single_binary_main_paste"  -Dusage=_usage_paste $(src_coreutils_CFLAGS)
# Command pathchk
noinst_LIBRARIES += src/libsinglebin_pathchk.a
src_libsinglebin_pathchk_a_SOURCES = src/pathchk.c
src_libsinglebin_pathchk_a_CFLAGS = "-Dmain=single_binary_main_pathchk (int, char **);  int single_binary_main_pathchk"  -Dusage=_usage_pathchk $(src_coreutils_CFLAGS)
# Command pr
noinst_LIBRARIES += src/libsinglebin_pr.a
src_libsinglebin_pr_a_SOURCES = src/pr.c
src_libsinglebin_pr_a_ldadd =   $(LIB_CLOCK_GETTIME)
src_libsinglebin_pr_a_CFLAGS = "-Dmain=single_binary_main_pr (int, char **);  int single_binary_main_pr"  -Dusage=_usage_pr $(src_coreutils_CFLAGS)
# Command printenv
noinst_LIBRARIES += src/libsinglebin_printenv.a
src_libsinglebin_printenv_a_SOURCES = src/printenv.c
src_libsinglebin_printenv_a_CFLAGS = "-Dmain=single_binary_main_printenv (int, char **);  int single_binary_main_printenv"  -Dusage=_usage_printenv $(src_coreutils_CFLAGS)
# Command printf
noinst_LIBRARIES += src/libsinglebin_printf.a
src_libsinglebin_printf_a_SOURCES = src/printf.c
src_libsinglebin_printf_a_ldadd =   $(LIBICONV)
src_libsinglebin_printf_a_CFLAGS = "-Dmain=single_binary_main_printf (int, char **);  int single_binary_main_printf"  -Dusage=_usage_printf $(src_coreutils_CFLAGS)
# Command ptx
noinst_LIBRARIES += src/libsinglebin_ptx.a
src_libsinglebin_ptx_a_SOURCES = src/ptx.c
src_libsinglebin_ptx_a_ldadd =   $(LIBICONV)
src_libsinglebin_ptx_a_CFLAGS = "-Dmain=single_binary_main_ptx (int, char **);  int single_binary_main_ptx"  -Dusage=_usage_ptx $(src_coreutils_CFLAGS)
# Command pwd
noinst_LIBRARIES += src/libsinglebin_pwd.a
src_libsinglebin_pwd_a_SOURCES = src/pwd.c
src_libsinglebin_pwd_a_CFLAGS = "-Dmain=single_binary_main_pwd (int, char **);  int single_binary_main_pwd"  -Dusage=_usage_pwd $(src_coreutils_CFLAGS)
# Command readlink
noinst_LIBRARIES += src/libsinglebin_readlink.a
src_libsinglebin_readlink_a_SOURCES = src/readlink.c
src_libsinglebin_readlink_a_CFLAGS = "-Dmain=single_binary_main_readlink (int, char **);  int single_binary_main_readlink"  -Dusage=_usage_readlink $(src_coreutils_CFLAGS)
# Command realpath
noinst_LIBRARIES += src/libsinglebin_realpath.a
src_libsinglebin_realpath_a_SOURCES =   src/realpath.c src/relpath.c src/relpath.h
src_libsinglebin_realpath_a_CFLAGS = "-Dmain=single_binary_main_realpath (int, char **);  int single_binary_main_realpath"  -Dusage=_usage_realpath $(src_coreutils_CFLAGS)
# Command rm
noinst_LIBRARIES += src/libsinglebin_rm.a
src_libsinglebin_rm_a_SOURCES =   src/rm.c src/remove.c
src_libsinglebin_rm_a_ldadd =   $(remove_ldadd)
src_libsinglebin_rm_a_CFLAGS = "-Dmain=single_binary_main_rm (int, char **);  int single_binary_main_rm"  -Dusage=_usage_rm $(src_coreutils_CFLAGS)
# Command rmdir
noinst_LIBRARIES += src/libsinglebin_rmdir.a
src_libsinglebin_rmdir_a_SOURCES =   src/rmdir.c src/prog-fprintf.c
src_libsinglebin_rmdir_a_CFLAGS = "-Dmain=single_binary_main_rmdir (int, char **);  int single_binary_main_rmdir"  -Dusage=_usage_rmdir $(src_coreutils_CFLAGS)
# Command runcon
noinst_LIBRARIES += src/libsinglebin_runcon.a
src_libsinglebin_runcon_a_SOURCES = src/runcon.c
src_libsinglebin_runcon_a_ldadd =   $(LIB_SELINUX)
src_libsinglebin_runcon_a_CFLAGS = "-Dmain=single_binary_main_runcon (int, char **);  int single_binary_main_runcon"  -Dusage=_usage_runcon $(src_coreutils_CFLAGS)
# Command seq
noinst_LIBRARIES += src/libsinglebin_seq.a
src_libsinglebin_seq_a_SOURCES = src/seq.c
src_libsinglebin_seq_a_CFLAGS = "-Dmain=single_binary_main_seq (int, char **);  int single_binary_main_seq"  -Dusage=_usage_seq $(src_coreutils_CFLAGS)
# Command sha1sum
noinst_LIBRARIES += src/libsinglebin_sha1sum.a
src_libsinglebin_sha1sum_a_SOURCES =   src/md5sum.c
src_libsinglebin_sha1sum_a_ldadd =   $(LIB_CRYPTO)
src_libsinglebin_sha1sum_a_CFLAGS = "-Dmain=single_binary_main_sha1sum (int, char **);  int single_binary_main_sha1sum"  -Dusage=_usage_sha1sum $(src_coreutils_CFLAGS)
src_libsinglebin_sha1sum_a_CPPFLAGS =   -DHASH_ALGO_SHA1=1 $(AM_CPPFLAGS)
# Command sha224sum
noinst_LIBRARIES += src/libsinglebin_sha224sum.a
src_libsinglebin_sha224sum_a_SOURCES =   src/md5sum.c
src_libsinglebin_sha224sum_a_ldadd =   $(LIB_CRYPTO)
src_libsinglebin_sha224sum_a_CFLAGS = "-Dmain=single_binary_main_sha224sum (int, char **);  int single_binary_main_sha224sum"  -Dusage=_usage_sha224sum $(src_coreutils_CFLAGS)
src_libsinglebin_sha224sum_a_CPPFLAGS =   -DHASH_ALGO_SHA224=1 $(AM_CPPFLAGS)
# Command sha256sum
noinst_LIBRARIES += src/libsinglebin_sha256sum.a
src_libsinglebin_sha256sum_a_SOURCES =   src/md5sum.c
src_libsinglebin_sha256sum_a_ldadd =   $(LIB_CRYPTO)
src_libsinglebin_sha256sum_a_CFLAGS = "-Dmain=single_binary_main_sha256sum (int, char **);  int single_binary_main_sha256sum"  -Dusage=_usage_sha256sum $(src_coreutils_CFLAGS)
src_libsinglebin_sha256sum_a_CPPFLAGS =   -DHASH_ALGO_SHA256=1 $(AM_CPPFLAGS)
# Command sha384sum
noinst_LIBRARIES += src/libsinglebin_sha384sum.a
src_libsinglebin_sha384sum_a_SOURCES =   src/md5sum.c
src_libsinglebin_sha384sum_a_ldadd =   $(LIB_CRYPTO)
src_libsinglebin_sha384sum_a_CFLAGS = "-Dmain=single_binary_main_sha384sum (int, char **);  int single_binary_main_sha384sum"  -Dusage=_usage_sha384sum $(src_coreutils_CFLAGS)
src_libsinglebin_sha384sum_a_CPPFLAGS =   -DHASH_ALGO_SHA384=1 $(AM_CPPFLAGS)
# Command sha512sum
noinst_LIBRARIES += src/libsinglebin_sha512sum.a
src_libsinglebin_sha512sum_a_SOURCES =   src/md5sum.c
src_libsinglebin_sha512sum_a_ldadd =   $(LIB_CRYPTO)
src_libsinglebin_sha512sum_a_CFLAGS = "-Dmain=single_binary_main_sha512sum (int, char **);  int single_binary_main_sha512sum"  -Dusage=_usage_sha512sum $(src_coreutils_CFLAGS)
src_libsinglebin_sha512sum_a_CPPFLAGS =   -DHASH_ALGO_SHA512=1 $(AM_CPPFLAGS)
# Command shred
noinst_LIBRARIES += src/libsinglebin_shred.a
src_libsinglebin_shred_a_SOURCES = src/shred.c
src_libsinglebin_shred_a_ldadd =   $(LIB_FDATASYNC)
src_libsinglebin_shred_a_CFLAGS = "-Dmain=single_binary_main_shred (int, char **);  int single_binary_main_shred"  -Dusage=_usage_shred $(src_coreutils_CFLAGS)
# Command shuf
noinst_LIBRARIES += src/libsinglebin_shuf.a
src_libsinglebin_shuf_a_SOURCES = src/shuf.c
src_libsinglebin_shuf_a_CFLAGS = "-Dmain=single_binary_main_shuf (int, char **);  int single_binary_main_shuf"  -Dusage=_usage_shuf $(src_coreutils_CFLAGS)
# Command sleep
noinst_LIBRARIES += src/libsinglebin_sleep.a
src_libsinglebin_sleep_a_SOURCES = src/sleep.c
src_libsinglebin_sleep_a_ldadd =   $(LIB_NANOSLEEP)
src_libsinglebin_sleep_a_CFLAGS = "-Dmain=single_binary_main_sleep (int, char **);  int single_binary_main_sleep"  -Dusage=_usage_sleep $(src_coreutils_CFLAGS)
# Command sort
noinst_LIBRARIES += src/libsinglebin_sort.a
src_libsinglebin_sort_a_SOURCES = src/sort.c
src_libsinglebin_sort_a_ldadd =   $(LIB_EACCESS)  $(LIB_NANOSLEEP)  $(LIB_CRYPTO)  $(LIB_PTHREAD)
src_libsinglebin_sort_a_CFLAGS = "-Dmain=single_binary_main_sort (int, char **);  int single_binary_main_sort"  -Dusage=_usage_sort $(src_coreutils_CFLAGS)
# Command split
noinst_LIBRARIES += src/libsinglebin_split.a
src_libsinglebin_split_a_SOURCES = src/split.c
src_libsinglebin_split_a_CFLAGS = "-Dmain=single_binary_main_split (int, char **);  int single_binary_main_split"  -Dusage=_usage_split $(src_coreutils_CFLAGS)
# Command stat
noinst_LIBRARIES += src/libsinglebin_stat.a
src_libsinglebin_stat_a_SOURCES =   src/stat.c src/find-mount-point.c
src_libsinglebin_stat_a_ldadd =   $(LIB_SELINUX)  $(LIB_NVPAIR)
src_libsinglebin_stat_a_CFLAGS = "-Dmain=single_binary_main_stat (int, char **);  int single_binary_main_stat"  -Dusage=_usage_stat $(src_coreutils_CFLAGS)
# Command sum
noinst_LIBRARIES += src/libsinglebin_sum.a
src_libsinglebin_sum_a_SOURCES = src/sum.c
src_libsinglebin_sum_a_CFLAGS = "-Dmain=single_binary_main_sum (int, char **);  int single_binary_main_sum"  -Dusage=_usage_sum $(src_coreutils_CFLAGS)
# Command sync
noinst_LIBRARIES += src/libsinglebin_sync.a
src_libsinglebin_sync_a_SOURCES = src/sync.c
src_libsinglebin_sync_a_ldadd =   $(LIB_FDATASYNC)
src_libsinglebin_sync_a_CFLAGS = "-Dmain=single_binary_main_sync (int, char **);  int single_binary_main_sync"  -Dusage=_usage_sync $(src_coreutils_CFLAGS)
# Command tac
noinst_LIBRARIES += src/libsinglebin_tac.a
src_libsinglebin_tac_a_SOURCES = src/tac.c
src_libsinglebin_tac_a_CFLAGS = "-Dmain=single_binary_main_tac (int, char **);  int single_binary_main_tac"  -Dusage=_usage_tac $(src_coreutils_CFLAGS)
# Command tail
noinst_LIBRARIES += src/libsinglebin_tail.a
src_libsinglebin_tail_a_SOURCES = src/tail.c
src_libsinglebin_tail_a_ldadd =   $(LIB_NANOSLEEP)
src_libsinglebin_tail_a_CFLAGS = "-Dmain=single_binary_main_tail (int, char **);  int single_binary_main_tail"  -Dusage=_usage_tail $(src_coreutils_CFLAGS)
# Command tee
noinst_LIBRARIES += src/libsinglebin_tee.a
src_libsinglebin_tee_a_SOURCES = src/tee.c
src_libsinglebin_tee_a_CFLAGS = "-Dmain=single_binary_main_tee (int, char **);  int single_binary_main_tee"  -Dusage=_usage_tee $(src_coreutils_CFLAGS)
# Command test
noinst_LIBRARIES += src/libsinglebin_test.a
src_libsinglebin_test_a_SOURCES = src/test.c
src_libsinglebin_test_a_ldadd =   $(LIB_EACCESS)
src_libsinglebin_test_a_CFLAGS = "-Dmain=single_binary_main_test (int, char **);  int single_binary_main_test"  -Dusage=_usage_test $(src_coreutils_CFLAGS)
# Command touch
noinst_LIBRARIES += src/libsinglebin_touch.a
src_libsinglebin_touch_a_SOURCES = src/touch.c
src_libsinglebin_touch_a_ldadd =   $(LIB_CLOCK_GETTIME)
src_libsinglebin_touch_a_CFLAGS = "-Dmain=single_binary_main_touch (int, char **);  int single_binary_main_touch"  -Dusage=_usage_touch $(src_coreutils_CFLAGS)
# Command tr
noinst_LIBRARIES += src/libsinglebin_tr.a
src_libsinglebin_tr_a_SOURCES = src/tr.c
src_libsinglebin_tr_a_CFLAGS = "-Dmain=single_binary_main_tr (int, char **);  int single_binary_main_tr"  -Dusage=_usage_tr $(src_coreutils_CFLAGS)
# Command true
noinst_LIBRARIES += src/libsinglebin_true.a
src_libsinglebin_true_a_SOURCES = src/true.c
src_libsinglebin_true_a_CFLAGS = "-Dmain=single_binary_main_true (int, char **);  int single_binary_main_true"  -Dusage=_usage_true $(src_coreutils_CFLAGS)
# Command truncate
noinst_LIBRARIES += src/libsinglebin_truncate.a
src_libsinglebin_truncate_a_SOURCES = src/truncate.c
src_libsinglebin_truncate_a_CFLAGS = "-Dmain=single_binary_main_truncate (int, char **);  int single_binary_main_truncate"  -Dusage=_usage_truncate $(src_coreutils_CFLAGS)
# Command tsort
noinst_LIBRARIES += src/libsinglebin_tsort.a
src_libsinglebin_tsort_a_SOURCES = src/tsort.c
src_libsinglebin_tsort_a_CFLAGS = "-Dmain=single_binary_main_tsort (int, char **);  int single_binary_main_tsort"  -Dusage=_usage_tsort $(src_coreutils_CFLAGS)
# Command tty
noinst_LIBRARIES += src/libsinglebin_tty.a
src_libsinglebin_tty_a_SOURCES = src/tty.c
src_libsinglebin_tty_a_CFLAGS = "-Dmain=single_binary_main_tty (int, char **);  int single_binary_main_tty"  -Dusage=_usage_tty $(src_coreutils_CFLAGS)
# Command uname
noinst_LIBRARIES += src/libsinglebin_uname.a
src_libsinglebin_uname_a_SOURCES =   src/uname.c src/uname-uname.c
src_libsinglebin_uname_a_ldadd =   $(GETHOSTNAME_LIB)
src_libsinglebin_uname_a_CFLAGS = "-Dmain=single_binary_main_uname (int, char **);  int single_binary_main_uname"  -Dusage=_usage_uname $(src_coreutils_CFLAGS)
# Command unexpand
noinst_LIBRARIES += src/libsinglebin_unexpand.a
src_libsinglebin_unexpand_a_SOURCES =   src/unexpand.c src/expand-common.c
src_libsinglebin_unexpand_a_CFLAGS = "-Dmain=single_binary_main_unexpand (int, char **);  int single_binary_main_unexpand"  -Dusage=_usage_unexpand $(src_coreutils_CFLAGS)
# Command uniq
noinst_LIBRARIES += src/libsinglebin_uniq.a
src_libsinglebin_uniq_a_SOURCES = src/uniq.c
src_libsinglebin_uniq_a_CFLAGS = "-Dmain=single_binary_main_uniq (int, char **);  int single_binary_main_uniq"  -Dusage=_usage_uniq $(src_coreutils_CFLAGS)
# Command unlink
noinst_LIBRARIES += src/libsinglebin_unlink.a
src_libsinglebin_unlink_a_SOURCES = src/unlink.c
src_libsinglebin_unlink_a_CFLAGS = "-Dmain=single_binary_main_unlink (int, char **);  int single_binary_main_unlink"  -Dusage=_usage_unlink $(src_coreutils_CFLAGS)
# Command vdir
noinst_LIBRARIES += src/libsinglebin_vdir.a
src_libsinglebin_vdir_a_SOURCES = src/coreutils-vdir.c
src_libsinglebin_vdir_a_ldadd =   $(src_ls_LDADD) src/libsinglebin_ls.a
src_libsinglebin_vdir_a_CFLAGS = "-Dmain=single_binary_main_vdir (int, char **);  int single_binary_main_vdir"  -Dusage=_usage_vdir $(src_coreutils_CFLAGS)
# Command wc
noinst_LIBRARIES += src/libsinglebin_wc.a
src_libsinglebin_wc_a_SOURCES = src/wc.c
src_libsinglebin_wc_a_CFLAGS = "-Dmain=single_binary_main_wc (int, char **);  int single_binary_main_wc"  -Dusage=_usage_wc $(src_coreutils_CFLAGS)
# Command whoami
noinst_LIBRARIES += src/libsinglebin_whoami.a
src_libsinglebin_whoami_a_SOURCES = src/whoami.c
src_libsinglebin_whoami_a_CFLAGS = "-Dmain=single_binary_main_whoami (int, char **);  int single_binary_main_whoami"  -Dusage=_usage_whoami $(src_coreutils_CFLAGS)
# Command yes
noinst_LIBRARIES += src/libsinglebin_yes.a
src_libsinglebin_yes_a_SOURCES = src/yes.c
src_libsinglebin_yes_a_CFLAGS = "-Dmain=single_binary_main_yes (int, char **);  int single_binary_main_yes"  -Dusage=_usage_yes $(src_coreutils_CFLAGS)
